paytm.payment:
  sandbox:
    merchantId: XQdUOk98197679497278
    merchantKey: _WCbmBOuhQ2hThn3
    channelId: WEB
    website: WEBSTAGING
    industryTypeId: Retail
    paytmUrl:  https://securegw-stage.paytm.in/order/process
    callbackUrl: http://local host:8080/pgresponse
    details:
      MID: ${paytm.payment.sandbox.merchantId}
      CHANNEL_ID: ${paytm.payment.sandbox.channelId}
      INDUSTRY_TYPE_ID: ${paytm.payment.sandbox.industryTypeId}
      WEBSITE: ${paytm.payment.sandbox.website}
      CALLBACK_URL: ${paytm.payment.sandbox.callbackUrl}